# Generated by Django 3.2.9 on 2021-11-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_heading', models.CharField(max_length=50)),
                ('blog_image', models.ImageField(upload_to='pics')),
                ('blog_des', models.TextField(max_length=1000)),
                ('blog_date', models.DateTimeField(auto_now_add=True)),
                ('blog_publisher', models.CharField(max_length=20)),
            ],
        ),
    ]
